package com.saleh.wadhkur;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.Typeface;import android.net.Uri;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;
public class MainActivity extends Activity{
 private static final int BG=Color.rgb(5,10,18),GREEN=Color.rgb(57,255,143),CYAN=Color.rgb(55,220,255),PURPLE=Color.rgb(169,92,255),WHITE=Color.rgb(239,250,245),MUTED=Color.rgb(159,178,188);private android.content.SharedPreferences prefs;private TextView countText,statusText;
 public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("settings",MODE_PRIVATE);showHome();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},44);}
 private void showHome(){setContentView(R.layout.activity_main);countText=findViewById(R.id.countText);statusText=findViewById(R.id.statusText);findViewById(R.id.morningBtn).setOnClickListener(v->section("🌅 أذكار الصباح",DhikrData.MORNING));findViewById(R.id.eveningBtn).setOnClickListener(v->section("🌆 أذكار المساء",DhikrData.EVENING));findViewById(R.id.duasBtn).setOnClickListener(v->section("🤲 الأدعية",DhikrData.DUAS));findViewById(R.id.surasBtn).setOnClickListener(v->section("📖 السور والآيات",DhikrData.SURAS));findViewById(R.id.tasbeehBtn).setOnClickListener(v->tasbeeh());findViewById(R.id.settingsBtn).setOnClickListener(v->settings());findViewById(R.id.aboutBtn).setOnClickListener(v->about());refresh();}
 private void refresh(){String d=today();if(!d.equals(prefs.getString("date","")))prefs.edit().putString("date",d).putInt("count",0).apply();countText.setText(String.valueOf(prefs.getInt("count",0)));boolean e=prefs.getBoolean("enabled",false);long m=prefs.getLong("minutes",30);statusText.setText(e?"🟢 نشط الآن • تذكير كل "+m+" دقيقة":"⚪ التذكيرات متوقفة");statusText.setTextColor(e?GREEN:MUTED);}
 private void section(String title,DhikrData.Dhikr[] data){ScrollView s=new ScrollView(this);s.setBackgroundColor(BG);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(14),dp(8),dp(14),dp(28));r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);TextView back=label("‹",GREEN,42,true);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->showHome());TextView h=label(title,WHITE,24,true);h.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);bar.addView(h,new LinearLayout.LayoutParams(0,dp(62),1));bar.addView(back,new LinearLayout.LayoutParams(dp(54),dp(62)));r.addView(bar);TextView n=label("كل بطاقة مستقلة — اضغط حتى يكتمل العدد",MUTED,14,false);n.setGravity(Gravity.RIGHT);n.setPadding(0,0,0,dp(12));r.addView(n);for(DhikrData.Dhikr x:data)r.addView(card(x));s.addView(r);setContentView(s);}
 private View card(DhikrData.Dhikr x){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(17),dp(16),dp(17),dp(16));c.setBackgroundResource(R.drawable.card_bg);c.setElevation(dp(3));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(14));c.setLayoutParams(cp);TextView t=label(x.title,GREEN,19,true),body=label(x.text,WHITE,18,false);body.setLineSpacing(dp(3),1.14f);body.setPadding(0,dp(10),0,dp(10));TextView src=label("المصدر: "+x.source,CYAN,12,false),p=label(progress(0,x.count),PURPLE,17,true);p.setGravity(Gravity.CENTER);p.setPadding(0,dp(12),0,dp(7));Button a=new Button(this);a.setText("📿 اضغط للذكر");a.setTextColor(BG);a.setTextSize(16);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);a.setAllCaps(false);a.setBackgroundResource(R.drawable.neon_button);c.addView(t);c.addView(body);c.addView(src);c.addView(p);c.addView(a,new LinearLayout.LayoutParams(-1,dp(54)));final int[] q={0};a.setOnClickListener(v->{if(q[0]>=x.count)return;q[0]++;recordDhikr(this);p.setText(progress(q[0],x.count));if(q[0]==x.count){a.setText("✓ اكتمل");a.setTextColor(WHITE);a.setBackgroundColor(Color.rgb(20,105,68));a.setEnabled(false);}});return c;}
 private void tasbeeh(){final int[] q={0};LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setGravity(Gravity.CENTER);b.setPadding(dp(24),dp(12),dp(24),dp(6));b.setBackgroundColor(BG);TextView n=label("0",GREEN,54,true);n.setGravity(Gravity.CENTER);b.addView(n,new LinearLayout.LayoutParams(-1,dp(100)));Button a=new Button(this);a.setText("📿 سبحان الله");a.setTextColor(BG);a.setTextSize(18);a.setAllCaps(false);a.setBackgroundResource(R.drawable.neon_button);a.setOnClickListener(v->{q[0]++;n.setText(String.valueOf(q[0]));recordDhikr(this);});b.addView(a,new LinearLayout.LayoutParams(-1,dp(58)));new AlertDialog.Builder(this).setTitle("عداد التسبيح").setView(b).setNegativeButton("إغلاق",null).show();}
 private void settings(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(22),0,dp(22),0);Switch e=new Switch(this);e.setText("تفعيل رفيق الذكر");e.setTextSize(17);e.setChecked(prefs.getBoolean("enabled",false));b.addView(e);TextView h=label("الفاصل: من 1 إلى 60 دقيقة (الافتراضي 30)",MUTED,14,false);h.setPadding(0,dp(12),0,dp(5));b.addView(h);EditText m=new EditText(this);m.setInputType(InputType.TYPE_CLASS_NUMBER);m.setText(String.valueOf(prefs.getLong("minutes",30)));m.setTextSize(18);b.addView(m);new AlertDialog.Builder(this).setTitle("🔔 رفيق الذكر").setView(b).setPositiveButton("حفظ",(d,w)->{long v=30;try{v=Long.parseLong(m.getText().toString().trim());}catch(Exception ignored){}v=Math.max(1,Math.min(60,v));boolean on=e.isChecked();prefs.edit().putBoolean("enabled",on).putLong("minutes",v).apply();if(on)ReminderScheduler.schedule(this,v);else ReminderScheduler.cancel(this);refresh();}).setNegativeButton("إلغاء",null).show();}
 private void about(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setGravity(Gravity.CENTER);b.setPadding(dp(22),dp(5),dp(22),dp(5));TextView n=label("وذكر 2.0.0",GREEN,27,true);n.setGravity(Gravity.CENTER);b.addView(n);TextView d=label("تطبيق إسلامي بسيط للأذكار والأدعية، مصمم ليكون سريعًا وواضحًا ومريحًا للاستخدام اليومي.",WHITE,16,false);d.setGravity(Gravity.CENTER);d.setPadding(0,dp(12),0,dp(12));b.addView(d);TextView dev=label("المطور: صالح الخليفي",CYAN,16,true);dev.setGravity(Gravity.CENTER);b.addView(dev);TextView tg=label("Telegram: @iSx3i",GREEN,17,true);tg.setGravity(Gravity.CENTER);tg.setPadding(0,dp(16),0,dp(5));tg.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://t.me/iSx3i")));}catch(Exception ignored){}});b.addView(tg);new AlertDialog.Builder(this).setTitle("ℹ️ حول التطبيق").setView(b).setPositiveButton("تم",null).show();}
 private TextView label(String x,int color,float size,boolean bold){TextView v=new TextView(this);v.setText(x);v.setTextColor(color);v.setTextSize(size);v.setGravity(Gravity.RIGHT);v.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
 private String progress(int c,int total){StringBuilder s=new StringBuilder();for(int i=0;i<total;i++)s.append(i<c?"● ":"○ ");if(c>=total){s.append("✓");return s.toString();}s.append(c).append("/").append(total);return s.toString();}
 public static void recordDhikr(Context c){android.content.SharedPreferences p=c.getSharedPreferences("settings",MODE_PRIVATE);String d=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());if(!d.equals(p.getString("date","")))p.edit().putString("date",d).putInt("count",0).apply();p.edit().putInt("count",p.getInt("count",0)+1).apply();}
 private String today(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+0.5f);}
}
